// A mock NIP-17 DM agent — a stand-in for a real kirby-node agent so the kirby-ui
// DM panel can be exercised end-to-end without the Rust daemon. It advertises a
// NIP-17 inbox (kind:10050) so the UI discovers + addresses it, listens for
// gift-wrapped DMs (kind:1059) addressed to it, and replies with a gift-wrapped
// "thinking" message — the exact wire shape the real agent (#73) uses, so the UI
// cannot tell this from the daemon's output.
//
// This is a DEV harness only; the real agent's reply is generated by its brain.
//
// Run (relay must be up):
//   bun mock/dm-agent.ts --relay ws://127.0.0.1:7799
//   KIRBY_RELAY=ws://host:7777 bun mock/dm-agent.ts
//
// bun provides a global WebSocket, so nostr-tools' relay client needs no polyfill.

import { finalizeEvent, generateSecretKey, getPublicKey } from "nostr-tools/pure";
import { SimplePool } from "nostr-tools/pool";
import { npubEncode } from "nostr-tools/nip19";
import { wrapEvent } from "nostr-tools/nip17";
import { unwrapEvent } from "nostr-tools/nip59";

function arg(flag: string, fallback: string): string {
  const i = process.argv.indexOf(flag);
  const v = i >= 0 ? process.argv[i + 1] : undefined;
  return v ?? fallback;
}

const relayUrl = process.env.KIRBY_RELAY ?? arg("--relay", "ws://127.0.0.1:7799");
const sk = generateSecretKey();
const pk = getPublicKey(sk);
const nowSec = () => Math.floor(Date.now() / 1000);

console.log("mock dm-agent");
console.log(`  relay: ${relayUrl}`);
console.log(`  npub:  ${npubEncode(pk)}`);
console.log(`  hex:   ${pk}`);

const pool = new SimplePool();

// Advertise a NIP-17 inbox-relay list so the UI can discover us and knows where to
// reach us. The signer of this event IS our DM npub.
const inbox = finalizeEvent({ kind: 10050, created_at: nowSec(), tags: [["relay", relayUrl]], content: "" }, sk);
await Promise.any(pool.publish([relayUrl], inbox));
console.log("published kind:10050 inbox");

// Listen for gift wraps addressed to us and reply to the seal-verified sender.
const seen = new Set<string>();
pool.subscribeMany(
  [relayUrl],
  { kinds: [1059], "#p": [pk] },
  {
    onevent(ev) {
      if (seen.has(ev.id)) return;
      seen.add(ev.id);
      try {
        const rumor = unwrapEvent(ev, sk);
        const sender = rumor.pubkey;
        if (sender === pk) return; // ignore anything we authored
        const text = (rumor as { content: string }).content;
        console.log(`◀ DM from ${sender.slice(0, 8)}…: ${text}`);
        const reply = `🤔 (mock agent) you said: "${text}". I'm a stand-in agent — a DM is quarantined, so I can think and chat but can't spend or post. Ask me anything.`;
        const replyWrap = wrapEvent(sk, { publicKey: sender }, reply);
        pool.publish([relayUrl], replyWrap);
        console.log(`▶ replied to ${sender.slice(0, 8)}…`);
      } catch (e) {
        console.error("failed to handle gift wrap:", e);
      }
    },
  },
);
console.log(`listening for gift wraps (#p=${pk.slice(0, 8)}…)`);
